### ISSUE TITLE
API reference for the components returns 404 

### ISSUE THREAD

**Issue by paschalidi** [dhis2/ui#157]
Hey all! 👋 

While I was trying to read the api specifications for some component from the https://ui.dhis2.nu/#/api I will get a 404 when clicking to the `SingleEvent` for instance. 

The link of the `SingleEvent` is [here](https://ui.dhis2.nu/#/module_core/src/SingleSelect/SingleSelect). 

I am happy to help with that :)

**Comment by ismay** [comment]
Thanks for reporting this @paschalidi. This was also mentioned in #119, with a potential fix, see here:

<img width="625" alt="Screenshot 2020-06-17 at 09 50 54" src="https://user-images.githubusercontent.com/7355199/84870859-1b630c80-b080-11ea-9ef0-e7ead30e1b40.png">

The fix should be fairly simple, it seems that it's just a matter of moving some docsite configuration. Feel free to submit a PR for this (or ask for more info in the ui channel), would be greatly appreciated! I'll close this issue so that we don't have any duplicates.

**Comment by paschalidi** [comment]
Hey sorry, didnt see that @ismay

**Comment by ismay** [comment]
No problem 😊 Thanks for reporting it!
