### ISSUE TITLE
Our readme isn't being published with UI on npm

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#173]
See here: https://www.npmjs.com/package/@dhis2/ui

<img width="449" alt="Screenshot 2020-06-16 at 14 11 12" src="https://user-images.githubusercontent.com/7355199/84772462-4182a100-afdb-11ea-9287-9c027ed9936f.png">

Same goes for ui-core, ui-constants and ui-icons.

**Comment by amcgee** [comment]
This is because there's no README in the `packages/xyz` directories

**Comment by amcgee** [comment]
[ui-widgets](https://github.com/dhis2/ui/blob/master/packages/widgets/README.md) and [ui-forms](https://github.com/dhis2/ui/blob/master/packages/forms/README.md) do have them, though they point to old documentations links.  They should also recommend that people use `ui` instead of `ui-xyz` I think!

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-51
