### ISSUE TITLE
Using props to overwrite context

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/ui#218]
> I would expect a table to have (or not have) zebra striping in its entirety. Is there a reason that the setting can be overridden with a prop on an individual TableRow as well? I would expect users to always use the TableRow with our Table.
> (Ismay)

> It's because we've defined that we won't use context unless it's overwritable by props and that props always have priority over context. @varl didn't want to have context in the core library at first until we agreed on the compromise to allow context as long as it can be overwritten with props.
> (Jan-Gerke)

> Ah, I didn't know that. Ok, I understand the intention. It keeps our components under user control at the component-level if they want that.
> 
> I do think that it makes for a bit of a confusing api though. It feels like we're using context to allow our components to communicate, so that we can have a simple top-level api on the Table component. Feels like that design intention runs kind of contrary to having components that are completely isolated. A bit like we're designing two different types of APIs.
> 
> I think we have that issue in some of our other components as well. Maybe we should discuss that on a more global level. Maybe you could say that one is the expected usage, and the other an escape hatch for more experienced devs? Though I wonder in what situation a dev would want to override the context and set the prop themselves.
> 
> _Originally posted by @ismay in https://github.com/dhis2/ui/pull/211#discussion_r457912285_

Continuing the discussion here:
Should we allow to override context logic or is the api confusing and unnecessary?

**Comment by varl** [comment]
The reason we "opened" the door for context-driven components was in part because the line between an "atom" component and a "molecule" component was blurry and hard to keep separate from each other.

From the user side, there were complaints that it was too verbose to be explicit for each prop at each level of the molecule. Such feedback is also valid, which was another reason that we introduced a context-driven approach.

Now that the UI libraries are organized in a monorepo, the developer problem were one would have to orchestrate a number of PRs in various repositories to keep the APIs isolated and the core/widget line sharp should also be resolved.

The proposed Base components helps drive this separation:

- Base components: prop-driven (with property spreading)
- Core components: context-driven (through internal runtime Providers)
- Widgets: context-driven (through app-runtime Provider)

Such a separation makes sense to me from a few perspectives, including: code organization, package separation, API consistency, usability for consumers, and developer productivity.

**Comment by ismay** [comment]
>     Base components: prop-driven (with property spreading)
>     Core components: context-driven (through internal runtime Providers)
>     Widgets: context-driven (through app-runtime Provider)
> 
> Such a separation makes sense to me from a few perspectives, including: code organization, package separation, API consistency, usability for consumers, and developer productivity.

So if I understand correctly, you'd also be in favor of omitting the override on each `<Tablerow>`? That was the core of my question in the original PR. The TableRow took the value for zebrastriping from the Table via context, but then also accepted a prop that could override that value.

It seemed confusing to me, since it's something I'd expect to be toggled at the Table level. And I also didn't see an obvious usecase for it. Jan-Gerke explained that it's a convention we have to allow that override. But if I understand correctly you'd be ok with us omitting that override?

**Comment by varl** [comment]
> It seemed confusing to me, since it's something I'd expect to be toggled at the Table level. And I also didn't see an obvious usecase for it. Jan-Gerke explained that it's a convention we have to allow that override. But if I understand correctly you'd be ok with us omitting that override?

While @Mohammer5's explanation is correct, it predates the monorepo and the discussion around base components. At the point in time we made that call, it was a trade-off to allow the use of context and maintain a prop-driven API.

Now that we have the concept of base components, the situation has changed, and given that we build base components that are purely props-driven; yes, the core components can omit the override and use a context internally to e.g. share the zebra-striping prop easily.

**Comment by Mohammer5** [comment]
So in case of the table row component, we could just extract it and make it a base component and then replace the existing `TableRow` with a component that uses both the context and the base component.

In terms of abstraction I think that makes sense, but I'm wondering if we really need this level of abstraction or if it's just extra work that we're doing without a real-life benefit. And this applies to the general concept of base components (maybe I misinterpreted what base components are, more on that at the bottom of this comment).

We haven't started working on base components yet, we "just" have the mono-repo in place so we could easily do it. From a pragmatic point of view I don't see a reason to extract base components until there's a need for them, because we already have to maintain so many libs and apps with very limited resources. Increasing the abstraction level adds another layer that we would have to take care of (although the base apps are not really complex or complicated). So in case of the table I think I would prefer having just a context-driven table (at least for the zebra striping) and completely omit the base component.

Maybe I misinterpreted what you guys meant with "base" components. Do you want to move all components there and then `core` only contains components that use context? Or are `base` components of abstract nature that wouldn't be used on their own unless the consumer wants to apply customizations or replicate our `core` components in a slightly different way?

**Comment by varl** [comment]
> Or are base components of abstract nature that wouldn't be used on their own unless the consumer wants to apply customizations or replicate our core components in a slightly different way?

The short answer to this question is, "yes".

The longer answer may derail this topic a bit, though in the aim of providing context I'll permit myself to put it here for now. If it spawns more questions than it answers I will hide this comment and extract the follow-ups to a separate topic.

By composing from base components, there are indeed advantages and disadvantages, a couple of notables ones include:

- We stay close to atomic design principles.

- It becomes clear how to contribute to the UI component library.
  The convention is clear in code and structure, and becomes easy to review for faults.

- Base components are simple to re-use across higher-level components.
  E.g. `TableRowBase` can be re-used across many different types of `Table` components.

- Extra work is required to organize a Core or Widget component with Base components if no Base components can be re-used.

- Apps can use existing Base components to build custom components and still leverage the benefits in terms of UI consistency, maintenance, and style updates.

An example from an [un-merged branch](https://github.com/dhis2/ui/blob/deprecate/set-control-fields/packages/core/src/ButtonBase/ButtonBase.js), though since it might be deleted, here it is for reference:

```jsx
const ButtonBase = React.forwardRef(
    (
        {
            children,
            className,
            primary,
            secondary,
            destructive,
            small,
            large,
            disabled,
            ...props
        },
        ref
    ) => (
        <button
            {...props}
            className={cx(className, {
                primary,
                secondary,
                destructive,
                small,
                large,
            })}
            disabled={disabled}
            ref={ref}
        >
            {children}
            <style jsx>{styles}</style>
        </button>
    )
)

ButtonBase.displayName = 'ButtonBase'
```

Note that this component is not necessarily the way they should be built, it is only a draft. There are some parts that will be in the final version though, notably forward refs, displayName, spreading props, and lack of attached behavior are explicit design goals to serve maximal flexibility. The final version should therefor be very similar to a HTML element in how flexible it is, with the addition that we bundle our styles with it.

Following that, Base components should therefor be flexible enough to be used as a building block for _all_ other Button components, e.g. `Button`, `DropdownButton`, `SplitButton`, `SuperMagicButton`, and so forth, both inside of the UI libraries and for custom needs in applications.

If someone is going to build a new button component, they _absolutely_ should use the existing base component over creating a new component where they are working on their new component.

Viewed from an isolated perspective of the UI library, the extra effort may be annoying, though with a wider lens and especially with a long-term view, the extra upfront effort should pay for itself many times over.

**Comment by Mohammer5** [comment]
I think we can close this one if favor of #222.
If we think it's still a valid issue after we've resolved the other issue, we can open this one again.
