### ISSUE TITLE
New feature: Org Unit Select Tree

### ISSUE THREAD

**Issue by plinnegan** [dhis2/ui#244]
Hi,

Really love the org unit tree component as it allows simple setup without even having to provide the full tree structure as a prop which is super!

For form workflow, I really enjoy the tree being collapsable in a select component, see here: https://ant.design/components/tree-select/

If this could be a new component that would be wonderful.

Thanks for all your hard work,
Pete

**Comment by Mohammer5** [comment]
Hey Pete,

sorry for the late reply! For now I'm not aware of any plans to do something like this (cc: @cooper-joe )
But you should be able to easily implement this with just a few steps. If you need more info about how to do that with the ui library, just let us know

**Comment by plinnegan** [comment]
Hi Jan-Gerke,

I would love to know how to implement this with the existing UI library, could you provide some more information?

Many thanks!
Pete

**Comment by HendrikThePendric** [comment]
Hi @plinnegan,

I've had a look at the ant-design page you linked too. I noticed some of these demos contain an input you can type in supposedly to provide a string-based filter. Typing in these inputs didn't have any effect so I'm not 100% sure ...

In any case, if what you are looking for requires filtering, this is currently not supported by the org unit tree, and would probably have to be incorporated into directly the core component, or perhaps the webapi.

However, if all you need is just a relatively small input-like component, that you can click on to show the org-unit tree, then I think some of our basic building block will get you quite far...

You could make this in various ways, there is no wrong or right, but I think this is how I'd do it in terms of components:
- You could just have a custom `div` and style it as an input with a dropdown icon. Essentially something like the Select's [`InputWrapper`](https://github.com/dhis2/ui/blob/master/packages/core/src/Select/InputWrapper.js), which is an internal component ATM unfortunately.
- For the selected org-units, you could show the displayValue of each selected orgUnit in a `Chip`, and allow for deselecting by clicking the `x` on the chip.
- Clicking the input would open a `Popover`, and in this you would show the `OrganisationUnitTree`

And some other considerations:
- Most of the time what you want for form-components is that they have a `value` and an `onChange` prop, so is a controlled-input and you can use it with various form-libraries or a stateful from-component.
- As such, probably the only state needed in the component you will build is the state to control whether or not the popover is showing.
- And finally, since you want to show the names of the selected org-units in the input-like component too, it is probably handy that you make sure to also include the orgUnit displayNames when you get the initial form data, i.e. `api/something?fields=organisationUnits[id,displayName]`

Hope this helps 😄

**Comment by plinnegan** [comment]
Hi @HendrikThePendric! The Ant demo filters the tree based on the value field by default rather than the title (If you view the code snippet you can see by entering some of the values in the data like '0-1' it filters all the nodes with values that partially match 0-1. I would just keep the values matching the titles and then the search would work as expected.

Thanks for your guidance on potential steps to making a simpler version of the component! I will give that a go when I have the time.

**Comment by HendrikThePendric** [comment]
Hi @plinnegan! 

I've just realised that our server already supports string based filtering, and that I have already produced a searchable version of the OrgUnit tree once (but not using our new UI library). However, I found that the UI pattern used on the Ant design demo is a bit hard to implement for us.

The problem is that we have to deal with lots of OrgUnits, sometimes 10.000s. As a consequence of this, our OrgUnitTree is fully async: child-nodes are being fetched on demand when the parent node opens. As such there is no "complete tree" that we can then filter on the client. String based filtering on the server works perfectly, but you just get a filtered list back without any guarantee that you could build a tree from that list. For example you could get an item that's nested 5 levels deep, but its parents are probably not included in the response*. So as a result I though it'd be best to split the UI up in two parts:
1. A Full org-unit-tree
2. A search input that returns a flat list of filtered org-units

You can see an example of the searchable org-unit tree I produced a few years ago here:
https://play.dhis2.org/dev/dhis-web-user/index.html#/users/new

And an example of getting a filtered list of orgUnits could be something like this:
https://play.dhis2.org/dev/api/organisationUnits.json?paging=false&filter=identifiable:token:sierra&fields=id,displayName,path

Whilst typing this, and experimenting a bit with the API, I have come to realise that if we tweaked the query a little bit, we could probably end up with a response that contains all the required data:
https://play.dhis2.org/dev/api/organisationUnits.json?paging=false&filter=identifiable:token:sierra&fields=id,displayName,path,ancestors[id,displayName,path]

With this we are also getting all the ancestors, so if we were to flatten and deduplicate this array you could build a full tree. This part probably doesn't even need to be async anymore, and we could use this logic to render a filtered tree.

Fancy contributing 😊 ?

**Comment by plinnegan** [comment]
Sounds great! So would we render the async tree until they searched something? Because they would want to see something initially in the drop down. Then swap to the filtered one after they enter more that 3 characters or something.

Would love to contribute if I can find the time! 😅

**Comment by HendrikThePendric** [comment]
👍  what you're suggesting makes perfect sense to me

**Comment by cooper-joe** [comment]
Adding my anecdata: a similar 'org-tree-in-select' pattern will be used in capture.app, so we could possibly include this a prebuilt component in `widgets`. However, as we would need to provide props for all the possible org-unit-tree configurations (single selection, filterable, multi-selection, recursive etc.), I think the resulting component may end up taking a lot of time to cover all the possible cases.

**Comment by varl** [comment]
This can be assembled using the core components and perhaps served as a custom package. If this is going to go into the UI library, we need to open an issue in JIRA.
