### ISSUE TITLE
Scrollbar showing in select at certain zoom levels

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#282]
See thread here: https://dhis2.slack.com/archives/CBM8LNEQM/p1600688471006400

<img width="535" alt="Screenshot 2020-09-21 at 13 40 19" src="https://user-images.githubusercontent.com/7355199/93764926-51ca9d80-fc14-11ea-9423-f5add39d558b.png">

At certain browser zoom levels the select shows a vertical scroll bar (see screenshot). This happens on ubuntu (maybe on other OSes as well).

**Comment by HendrikThePendric** [comment]
I’ll try some browsers on both MacOs and Ubuntu to get some idea of what’s affected. It seems to be a very specific issue:
- On MacOs all browsers are OK at all zoom levels
- On Ubuntu Firefox is OK at all zoom levels
- On Ubuntu Chrome is OK, apart from at 110% zoom

Or alternatively, this problem only happens when using Chrome on Ubuntu and having the browser at 110% zoom level.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-46
