### ISSUE TITLE
Revisit Select

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#64]
I've run into some bugs with the Select, and suspect that the old menu positioning logic and the new popper driven logic are clashing a bit. We've had an integration test for the Select fail randomly as well, so I want to take a good look at it and see if we can resolve the flakiness and ensure everything is working as expected.

**Comment by HendrikThePendric** [comment]
Good idea, I think it will be a challenge. See https://github.com/dhis2/ui/pull/60#issuecomment-626573168 for info.

I like the usage of a `ResizeObserver` in the Popper, to let the Popper adjust itself when required. But we did also try an alternative approach using a `renderId` / `renderCount` prop to force an update. This also worked fine, but makes for a much more quirky API and moves the responsibility for updating the position out of the popper and into whichever component is rendering the popper. This which isn't the most logical separation of concerns and will lead to code-bloat in the long term. If we can't work out a way of fixing these failing tests due to the `ResizeObserver` we could consider switching to that more quirky API instead (even though that'd be admitting defeat).

I think we should also look into the setup of our cypress environment... I'm not sure what we are doing now, but we were doing everything in `electron`, which usually used some older version of chromium. According to the docs we should be able to use Chrome.

**Comment by ismay** [comment]
Agreed. I did create this PR a while back, when testing running our cypress tests in FF and Chrome: https://github.com/dhis2/ui-core/pull/800

**Comment by ismay** [comment]
So about the cypress tests in Chrome (+ maybe FF, etc.), maybe we could split that into a separate issue. To not muddy the scope for the current one.
