### ISSUE TITLE
Rerunning cypress tests (GH actions) breaks

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#72]
Clicking Re-run jobs for the cypress GH actions breaks with the following error:

<img width="915" alt="Screenshot 2020-05-14 at 16 51 54" src="https://user-images.githubusercontent.com/7355199/81949528-3f57ac00-9603-11ea-8963-ce29297ac157.png">

See here for example: https://github.com/dhis2/ui/pull/66/checks?check_run_id=674857570

**Comment by HendrikThePendric** [comment]
I'm pretty sure I saw a related problem a while ago. I think it's related to [this bug in cypress](https://github.com/cypress-io/cypress/issues/6450). This bug is fixed in cypress 4.0.2, so when we upgrade `@dhis2/cli-utils-cypress`, [this should be fixed](https://github.com/dhis2/cli-utils-cypress/blob/master/package.json#L35).

We probably don't even have to take any specific action, once `v5.0.0` is released we'll just enable dependabot and this should happen automatically.

**Comment by varl** [comment]
I haven't seen this turn up in a while, considering it fixed. Re-report in JIRA if it does come back.
