### ISSUE TITLE
Use less (or simpler) test helpers

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#86]
This issue was created as a result of this https://github.com/dhis2/ui/pull/66#issuecomment-631385176. It would be good to start using less helpers in our tests code. I know that quite a lot of components have a `position.feature` file, and all of these make quite extensive usage of a helper. So that's one part that would definetely have to be addressed, but quite likely there's more.

**Comment by ismay** [comment]
To expand a bit on this, in the linked PR I was trying to follow up on the recommendations in this article: https://mtlynch.io/good-developers-bad-tests. Though factoring out often used code makes sense for production code, for tests it can be confusing. What I did in the PR was use a more basic helper, and copy/paste instead of abstracting. That (in my opinion) made the tests easier to read and reason about. I would propose we do this for all our tests.

**Comment by ismay** [comment]
On that note, I've introduced a `getAll` helper, but see that we have an `all` helper as well. At a glance, it seems like the `all` helper is a bit more useful (it allows more than just a get). If the `all` helper is stable I'd recommend removing the `getAll` helper whilst addressing this issue.

**Comment by HendrikThePendric** [comment]
@ismay I'm not sure if we should keep this issue open, and to which milestone we should add it. A lot of problems have been addressed already in https://github.com/dhis2/ui/pull/102, but that PR didn't really focus fully on removing the helper functions.

**Comment by ismay** [comment]
I'd vote to keep it open until it's been fully addressed. There are still test helpers remaining that we could potentially remove. Whether or not we should we should still discuss of course, but until then I'd say we could keep this open.

**Comment by ismay** [comment]
I'll add this to 5.1. Not really relevant to a specific release, but fits as a post major release task.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-57
