### ISSUE TITLE
Statusicon rendering causing alignment issues

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#89]
See this thread: https://dhis2.slack.com/archives/CBM8LNEQM/p1589961187000500

Two related problems:

### 1. Some of our field components have a margin-right to space the input and a potential icon:

- https://github.com/dhis2/ui-core/blob/05512df65f1a7f59dc4ee38b28927c1514896658/src/SingleSelect.js#L110
- https://github.com/dhis2/ui-core/blob/05512df65f1a7f59dc4ee38b28927c1514896658/src/MultiSelect.js#L110 (and maybe others)

This margin is always present, even if there's not an icon. We should make it conditional and not set a margin if there's no icon.

### 2. In the input we use a wrapper for the status-icon, which always renders a margin-left, throwing off alignment as well.

We should make this conditional as well, and should probably use the same approach everywhere. (Could be present in other components as well btw.)

https://github.com/dhis2/ui-core/blob/05512df65f1a7f59dc4ee38b28927c1514896658/src/Input.js#L68

See here: https://dhis2.slack.com/archives/CBM8LNEQM/p1589962613009000?thread_ts=1589961187.000500&cid=CBM8LNEQM

**Comment by HendrikThePendric** [comment]
> If you mean a conditional wrapper in the parent then that would be similar to the conditional margin-right, I'd prefer sth in that direction as well

I can't remember if that is exactly what I meant, but after reading this thread again, I do think that this approach makes most sense. Having a margin on the actual icon is probably a bad idea, for the reasons you mention. Having a wrapper with a (fixed) margin and conditionally rendering that would be the cleanest solution IMO, because if you used a dynamic/conditional margin we end up rendering an empty div with `margin-left: 0;` as its only style.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-80
